/* GENERATED by tools/assemble-courses.mjs from raw/units/lat-u*.json. Public-domain source. */
window.COURSE_DATA = (window.COURSE_DATA || { meta: { brand: "Euclidia", product: "Trivium" }, courses: [] });
window.COURSE_DATA.courses.push({
 "id": "lat",
 "title": "Latin Grammar",
 "subtitle": "Read real Latin from day one",
 "source": "Fr. W. G. Most, Latin by the Natural Method, First Year (1957), public domain",
 "license": "Public domain",
 "lang": "la",
 "units": [
  {
   "n": 1,
   "title": "Year One: Lectiones I-VI",
   "part": "Year One · Natural Method",
   "ref": "Most, Lectiones I-VI",
   "lessons": [
    {
     "title": "Nominative & Objective Case (Singular); Perfect Tense",
     "summary": "A first reading where third-person singular perfect verbs tell a tiny story, and word endings (not word order) mark the subject and the object.",
     "lead": "Watch how the subject stays plain while the object picks up an -m ending (agnus becomes agnum).",
     "original": "Maria habuit parvum agnum. Agnus fuit albus. Maria venit in scholam. Agnus venit in scholam. Agnus venit cum Maria. Marcus vidit agnum in schola. Agnus dixit: baa, baa.",
     "explanation": "Here is an English sentence: Marcus saw the lamb (Marcus vidit agnum). There are three important words in it. **Marcus** is the subject, so it is in the **nominative case**. The verb is saw. The object is lamb, so it is in the **objective case**. Notice that the Latin verbs above all end in -it, and that the word lamb in English comes after the verb. In Latin we do not depend on the order of the words to show the object. We depend on the ending. Notice that many words above end in -m: that is the ending for the object. Some have -am, some have -um, some have -em. We need not worry about the various nominative endings today, nor about the special endings used after words like ad, cum, and in. Notice also that Marcus is just one person, so the subject is **nominative singular**. There is also only one lamb, which is **objective singular**. More than one would be plural. There is no Latin word for the and no word for a or an, so just supply these in English when you need them.",
     "keyTerms": [
      {
       "term": "habuit",
       "def": "had"
      },
      {
       "term": "parvus",
       "def": "small, little"
      },
      {
       "term": "agnus",
       "def": "lamb"
      },
      {
       "term": "albus",
       "def": "white"
      },
      {
       "term": "fuit",
       "def": "was"
      },
      {
       "term": "venit",
       "def": "came"
      },
      {
       "term": "cum",
       "def": "with"
      },
      {
       "term": "vidit",
       "def": "saw"
      },
      {
       "term": "dixit",
       "def": "said"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'agnus' mean in this lesson?",
       "accept": [
        "lamb",
        "a lamb"
       ],
       "answer": "lamb",
       "why": "Most glosses agnus as 'lamb' in the vocabulary.",
       "src": "Most",
       "id": "lat-1-1-e1"
      },
      {
       "type": "type",
       "q": "What does the Latin word 'albus' mean in this lesson?",
       "accept": [
        "white"
       ],
       "answer": "white",
       "why": "Most glosses albus as 'white'; in the story the lamb is albus.",
       "src": "Most",
       "id": "lat-1-1-e2"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'saw'.",
       "accept": [
        "vidit"
       ],
       "answer": "vidit",
       "why": "Most glosses vidit as 'saw': 'Marcus vidit agnum in schola.'",
       "src": "Most",
       "id": "lat-1-1-e3"
      },
      {
       "type": "type",
       "q": "In the story, who had the little lamb? Answer in Latin.",
       "accept": [
        "Maria"
       ],
       "answer": "Maria",
       "why": "The story opens: 'Maria habuit parvum agnum.'",
       "src": "Most",
       "id": "lat-1-1-e4"
      },
      {
       "type": "type",
       "q": "In the story, who saw the lamb in school? Answer in Latin.",
       "accept": [
        "Marcus"
       ],
       "answer": "Marcus",
       "why": "The story says: 'Marcus vidit agnum in schola.'",
       "src": "Most",
       "id": "lat-1-1-e5"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story with the correct object form.",
       "text": "Maria habuit parvum ___.",
       "accept": [
        "agnum"
       ],
       "answer": "agnum",
       "why": "The story reads 'Maria habuit parvum agnum'; the object takes the -m ending.",
       "src": "Most",
       "id": "lat-1-1-e6"
      },
      {
       "type": "mc",
       "q": "In 'Marcus vidit agnum', which word is in the objective case?",
       "choices": [
        "Marcus",
        "vidit",
        "agnum",
        "in"
       ],
       "answer": 2,
       "why": "Agnum is the object of the verb, marked by the -m ending; Marcus is the nominative subject.",
       "src": "Most",
       "id": "lat-1-1-e7"
      }
     ],
     "id": "lat-1-1",
     "examples": []
    },
    {
     "title": "Plural Verbs & Objective Plural",
     "summary": "The Romans did not know the truth about Rome's founding: what Romulus and Remus did not do, the Etruscans did.",
     "lead": "Watch how the verbs end in -erunt when the subject is plural, and how objects in the plural take endings like -as, -os, and -es.",
     "original": "Roma fuit urbs magna. Romani amaverunt Romam. Roma fuit antiqua. Romani dixerunt quod Romulus et Remus fundaverunt Romam. Sed non dixerunt veritatem.\n\nIn anno millesimo ante Christum, viri iam fuerunt in terra Romana. Etrusci fundaverunt Romam. Etrusci amaverunt Romanos. Romani amaverunt terras Romanas. Sed non habuerunt urbes magnas.",
     "explanation": "**VERBS:** Last time we saw verbs ending in **-it**. They were singular, because their subject was singular. But when the subject is plural, the verb must be plural too. To make a verb plural, we change the ending **-it** to **-erunt**. We do not care whether the object is plural; that does not affect the verb. So we now have two verb endings: **-it** for singular and **-erunt** for plural. **NOUNS:** On nouns we can now have four different endings. We can have singular or plural for the subject (the **nominative** case), and singular or plural for the object (the **objective** case). Today we look only at the object patterns. Across the three families of nouns the objective endings are: singular **-am** and plural **-as**; singular **-um** and plural **-os**; singular **-em** and plural **-es**. Notice that some words are much longer in the objective case than in the nominative, for example **veritas** becomes **veritatem** and **urbs** becomes **urbem**. **ADJECTIVES and QUOD:** Words like **magnus** and **parvus** are adjectives; for now just get their meaning, which is easy. Notice also how **quod** was used. We have met it only in patterns such as he says that or he thinks that. We call this the dixit quod pattern for the indirect statement, in which we report, without quotation marks and in an inexact way, what someone says or thinks.",
     "keyTerms": [
      {
       "term": "amavit",
       "def": "loved"
      },
      {
       "term": "exclamavit",
       "def": "shouted"
      },
      {
       "term": "remansit",
       "def": "remained"
      },
      {
       "term": "domi",
       "def": "at home"
      },
      {
       "term": "hic",
       "def": "this"
      },
      {
       "term": "quod",
       "def": "that"
      },
      {
       "term": "ante",
       "def": "before"
      },
      {
       "term": "iam",
       "def": "already"
      },
      {
       "term": "annus",
       "def": "year"
      },
      {
       "term": "forum",
       "def": "market, forum"
      },
      {
       "term": "magnus",
       "def": "great, large"
      },
      {
       "term": "terra",
       "def": "land"
      },
      {
       "term": "urbs",
       "def": "city"
      },
      {
       "term": "vir",
       "def": "man"
      },
      {
       "term": "veritas",
       "def": "truth"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'urbs' mean in this lesson?",
       "accept": [
        "city",
        "a city"
       ],
       "answer": "city",
       "why": "The VOCABULARIUM glosses urbs as 'city', as in 'Roma fuit urbs magna'.",
       "src": "Most",
       "id": "lat-1-2-e1"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'truth'.",
       "accept": [
        "veritas",
        "veritatem"
       ],
       "answer": "veritas",
       "why": "The VOCABULARIUM gives veritas = truth; in the story it appears as 'non dixerunt veritatem'.",
       "src": "Most",
       "id": "lat-1-2-e2"
      },
      {
       "type": "type",
       "q": "What does the Latin word 'iam' mean in this lesson?",
       "accept": [
        "already"
       ],
       "answer": "already",
       "why": "The VOCABULARIUM glosses iam as 'already', as in 'viri iam fuerunt in terra Romana'.",
       "src": "Most",
       "id": "lat-1-2-e3"
      },
      {
       "type": "type",
       "q": "Qui fundaverunt Romam?",
       "accept": [
        "Etrusci",
        "the Etruscans",
        "Etruscans"
       ],
       "answer": "Etrusci",
       "why": "The story states the truth: 'Etrusci fundaverunt Romam.'",
       "src": "Most",
       "id": "lat-1-2-e4"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Romani ___ Romam.",
       "accept": [
        "amaverunt"
       ],
       "answer": "amaverunt",
       "why": "The story reads 'Romani amaverunt Romam.'",
       "src": "Most",
       "id": "lat-1-2-e5"
      },
      {
       "type": "mc",
       "q": "In this lesson, how do you change a perfect-tense verb from singular to plural?",
       "choices": [
        "Change the ending -it to -erunt",
        "Change the ending -it to -am",
        "Add the ending -os",
        "Change the ending -it to -e"
       ],
       "answer": 0,
       "why": "The grammar note says: 'To make the verbs plural, we change the ending -it to -erunt.'",
       "src": "Most",
       "id": "lat-1-2-e6"
      },
      {
       "type": "mc",
       "q": "Which set shows the PLURAL objective (object) endings taught in this lesson?",
       "choices": [
        "-as, -os, -es",
        "-am, -um, -em",
        "-a, -o, -e",
        "-it, -erunt"
       ],
       "answer": 0,
       "why": "The note lists the plural objective endings as -as, -os, and -es (singular forms are -am, -um, -em).",
       "src": "Most",
       "id": "lat-1-2-e7"
      }
     ],
     "id": "lat-1-2",
     "examples": []
    },
    {
     "title": "Ablative Singular & Prepositions",
     "summary": "Rome at first was ruled by Etruscan kings, but the last king, Tarquin, became arrogant, so the Romans drove him out.",
     "lead": "Watch the endings of the words after the preposition in (and after cum and ad) to see the new ablative case.",
     "original": "In primis annis Romani habuerunt reges. Reges fuerunt Etrusci. Etrusci erant in throno Romano. Etrusci regnaverunt in terra Romana. Primi reges fuerunt boni. Sed rex ultimus fuit malus. Hic rex ultimus fuit Tarquinius. Romani non amaverunt Tarquinium. Tarquinius fuit rex malus. Non fuit rex bonus. Non fuit rex magnus. Rex malus non est rex magnus. Rex malus est rex parvus. Tarquinius non fuit magnus. Fuit malus. Ergo Romani non amaverunt Tarquinium regem. Ante Tarquinium reges fuerunt boni. Sed Tarquinius non fuit bonus. Ergo Tarquinius non remansit in terra Romana. Tarquinius non amavit veritatem. Romani dixerunt quod Tarquinius fuit malus. Ergo non remansit in urbe. Sed Romani remanserunt in urbe.",
     "explanation": "There is not much new in this lesson, so let us catch up on a bit of old business. Notice the phrases **in terra Romana, in throno Romano, in urbe**. They all have the word **in**, which is a preposition. Notice the endings of the words that come after it: **a**, **o**, and **e**. They are in a special case, the **ablative case**. So we see three families of nouns again in the ablative, just as in the nominative and objective cases. The ablative singular endings here are **-a**, **-o**, and **-e**. The preposition **in** often (not always) takes the ablative case. Looking back at the first two lessons, we find other prepositions too. The preposition **cum** ALWAYS takes the ablative, while the preposition **ad** ALWAYS takes the objective case. But **in** sometimes takes the objective case instead. Compare **Maria venit in scholam** (Mary moves into somewhere, so objective) with **Maria fuit in schola** (Mary is stuck in one place, so ablative). When **in** means into, motion travelling into, it takes the objective; when **in** means in or on, with no motion, it takes the ablative.",
     "keyTerms": [
      {
       "term": "rex",
       "def": "king"
      },
      {
       "term": "primus",
       "def": "first"
      },
      {
       "term": "ultimus",
       "def": "last"
      },
      {
       "term": "malus",
       "def": "bad, evil"
      },
      {
       "term": "bonus",
       "def": "good"
      },
      {
       "term": "regnavit",
       "def": "ruled"
      },
      {
       "term": "erant",
       "def": "were"
      },
      {
       "term": "est",
       "def": "is"
      },
      {
       "term": "quando",
       "def": "when"
      },
      {
       "term": "Etrusci",
       "def": "Etruscans"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'rex' mean in this lesson?",
       "accept": [
        "king",
        "a king"
       ],
       "answer": "king",
       "why": "The vocabulary gives rex-king, as in 'Hic rex ultimus fuit Tarquinius.'",
       "src": "Most",
       "id": "lat-1-3-e1"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'last'.",
       "accept": [
        "ultimus"
       ],
       "answer": "ultimus",
       "why": "The vocabulary lists ultimus-last; 'Sed rex ultimus fuit malus.'",
       "src": "Most",
       "id": "lat-1-3-e2"
      },
      {
       "type": "type",
       "q": "What does the Latin word 'malus' mean in this lesson?",
       "accept": [
        "bad",
        "evil",
        "bad, evil"
       ],
       "answer": "bad",
       "why": "The vocabulary gives malus-bad, evil; 'Tarquinius fuit rex malus.'",
       "src": "Most",
       "id": "lat-1-3-e3"
      },
      {
       "type": "type",
       "q": "Quis fuit rex ultimus?",
       "accept": [
        "Tarquinius"
       ],
       "answer": "Tarquinius",
       "why": "The story says 'Hic rex ultimus fuit Tarquinius.'",
       "src": "Most",
       "id": "lat-1-3-e4"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Etrusci erant in throno ___.",
       "accept": [
        "Romano"
       ],
       "answer": "Romano",
       "why": "The story reads 'Etrusci erant in throno Romano.'",
       "src": "Most",
       "id": "lat-1-3-e5"
      },
      {
       "type": "mc",
       "q": "In the story, why does 'terra Romana' end in -a (in throno Romano, in urbe)?",
       "choices": [
        "It is in the ablative case after the preposition in",
        "It is in the objective case after the preposition ad",
        "It is in the nominative case as the subject",
        "It is plural"
       ],
       "answer": 0,
       "why": "After in with no motion the noun is ablative; the ablative singular endings here are -a, -o, -e.",
       "src": "Most",
       "id": "lat-1-3-e6"
      },
      {
       "type": "mc",
       "q": "Which case does the preposition 'cum' ALWAYS take?",
       "choices": [
        "The ablative case",
        "The objective case",
        "The nominative case",
        "The possessive case"
       ],
       "answer": 0,
       "why": "The grammar note says cum ALWAYS comes with the ablative case.",
       "src": "Most",
       "id": "lat-1-3-e7"
      }
     ],
     "id": "lat-1-3",
     "examples": []
    },
    {
     "title": "Reviewing the Perfect Tense and the Three Cases",
     "summary": "After the Romans expel Tarquin, war breaks out with the Etruscans, and Horatius holds the bridge to the city until it falls into the water.",
     "lead": "Watch how every verb ends in -it or -erunt (the perfect tense), and notice the objective and ablative endings on the nouns.",
     "original": "Postquam Romani expulerunt Tarquinium bellum habuerunt. Tarquinius enim Etruscus fuit. Ergo Etrusci venerunt ad bellum cum Romanis. Etrusci dixerunt quod Romani mali fuerunt: expulerunt Tarquinium. Romani dixerunt quod Tarquinius malus fuit: ergo expulerunt Tarquinium. Bellum non parvum fuit. Bellum fuit magnum. Multi viri magni fuerunt in bello. Viri Romani amaverunt Romam. Exclamaverunt quod Tarquinius malus tyrannus fuit. Viri Romani dixerunt veritatem. Tarquinius fuit tyrannus malus.\n\nEtiam rex Etruscus venit cum Tarquinio ad bellum. Rex Etruscus fuit Lars Porsenna. Romani viderunt exercitum Etruscum. Exercitus Etruscus magnus fuit. Romani viderunt quod exercitus Etruscus magnus fuit. Sed exercitus Romanus etiam magnus fuit. Viri Romani magni fuerunt. Sed viri Etrusci etiam magni fuerunt. Non parvi fuerunt. Ergo viri Romani et viri Etrusci paraverunt ad pugnam. Viri Etrusci dixerunt: Romani mali sunt: expulerunt Tarquinium. Sed Romani dixerunt quod Tarquinius malus fuit. Romani non agni fuerunt: viri fuerunt. Romani fuerunt ad urbem. Steterunt ad pontem. Etiam Etrusci steterunt ad pontem Romanum. Romani iecerunt ignem in pontem. Vir Romanus magnus stetit in ponte. Hic vir fuit Horatius. Amavit Romam. Sed Etrusci venerunt in pontem. Ignis venit in pontem. Pons cecidit in aquam. Horatius etiam cecidit in aquam.",
     "explanation": "**VERBS:** So far we have seen only two verb forms, those ending in **-it** and **-erunt**. They are the third person singular and the third person plural of the tense we call the **perfect**. The perfect tense refers to something that is past. **NOUNS:** We have used three cases. The **nominative** is the case for the subject. The **objective** is the case for the direct object of a verb, and it is also used for the object of some prepositions: ad, ante, and in (when in means into, with motion). The **ablative** case so far appears only after the prepositions cum and in (when in means in or on, with no motion). We already know the objective patterns in three declensions: 1. -am, -as; 2. -um, -os; 3. -em, -es. The ablative singular endings are: 1. -a; 2. -o; 3. -e. **ENIM:** Notice the odd word **enim**, which means for. It can never stand as the first word in its own clause. To say \"For the Romans were great,\" you may write Romani enim fuerunt magni, but never Enim Romani fuerunt magni.",
     "keyTerms": [
      {
       "term": "postquam",
       "def": "after"
      },
      {
       "term": "bellum",
       "def": "war"
      },
      {
       "term": "expulit",
       "def": "expelled"
      },
      {
       "term": "enim",
       "def": "for"
      },
      {
       "term": "etiam",
       "def": "even, also"
      },
      {
       "term": "exercitus",
       "def": "army"
      },
      {
       "term": "paravit",
       "def": "prepared"
      },
      {
       "term": "pugna",
       "def": "battle"
      },
      {
       "term": "stetit",
       "def": "stood"
      },
      {
       "term": "pons",
       "def": "bridge"
      },
      {
       "term": "ignis",
       "def": "fire"
      },
      {
       "term": "cecidit",
       "def": "fell"
      },
      {
       "term": "aqua",
       "def": "water"
      },
      {
       "term": "iecit",
       "def": "threw"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'pons' mean in this lesson?",
       "accept": [
        "bridge",
        "a bridge",
        "the bridge"
       ],
       "answer": "bridge",
       "why": "The vocabulary glosses pons as bridge.",
       "src": "Most",
       "id": "lat-1-4-e1"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'fire'.",
       "accept": [
        "ignis"
       ],
       "answer": "ignis",
       "why": "The vocabulary lists ignis = fire, as in 'Ignis venit in pontem.'",
       "src": "Most",
       "id": "lat-1-4-e2"
      },
      {
       "type": "type",
       "q": "Quis stetit in ponte et amavit Romam?",
       "accept": [
        "Horatius"
       ],
       "answer": "Horatius",
       "why": "The story says 'Vir Romanus magnus stetit in ponte. Hic vir fuit Horatius. Amavit Romam.'",
       "src": "Most",
       "id": "lat-1-4-e3"
      },
      {
       "type": "type",
       "q": "Quis fuit rex Etruscus?",
       "accept": [
        "Lars Porsenna",
        "Porsenna"
       ],
       "answer": "Lars Porsenna",
       "why": "The story says 'Rex Etruscus fuit Lars Porsenna.'",
       "src": "Most",
       "id": "lat-1-4-e4"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Pons cecidit in ___.",
       "accept": [
        "aquam"
       ],
       "answer": "aquam",
       "why": "The story reads 'Pons cecidit in aquam.'",
       "src": "Most",
       "id": "lat-1-4-e5"
      },
      {
       "type": "mc",
       "q": "The verb forms in this lesson end only in -it and -erunt. What tense are they?",
       "choices": [
        "Present",
        "Perfect",
        "Future",
        "Imperfect"
       ],
       "answer": 1,
       "why": "Most says these forms belong to the perfect tense, which refers to something past.",
       "src": "Most",
       "id": "lat-1-4-e6"
      },
      {
       "type": "mc",
       "q": "Which sentence correctly places the word 'enim'?",
       "choices": [
        "Enim Romani fuerunt magni.",
        "Romani enim fuerunt magni.",
        "Enim fuerunt magni Romani.",
        "Enim Romani magni fuerunt."
       ],
       "answer": 1,
       "why": "Most notes that enim can never be the first word in its clause, so only 'Romani enim fuerunt magni' is correct; the other three wrongly put enim first.",
       "src": "Most",
       "id": "lat-1-4-e7"
      }
     ],
     "id": "lat-1-4",
     "examples": []
    },
    {
     "title": "Ablative Plural",
     "summary": "After expelling the Etruscan kings, the Romans set up two consuls, but conflict between the rich patricians and the poor plebeians is only settled when the patricians create the tribunes of the people.",
     "lead": "Watch the ablative plural endings (-is and -ibus) on nouns, especially after prepositions like cum and in.",
     "original": "Romani expulerunt Etruscos. Nunc Etrusci non sunt reges in terra Romana. Romani non sunt reges in terra Romana, sed Romani fecerunt consules duos. Consules fuerunt viri boni. Reges Etrusci fuerunt mali. Sed consules non sunt mali: viri magni sunt. Consules habuerunt magnam potestatem. In urbe Romana cives pugnaverunt cum civibus. Romani patricii fuerunt divites: magnam pecuniam habuerunt. Patricii etiam magnam potestatem habuerunt. Sed plebs Romana fuerunt pauperes. Plebs non habuerunt pecuniam. Plebs non habuerunt potestatem in urbe. Plebs voluerunt potestatem. Plebs voluerunt pecuniam. Patricii non dederunt pecuniam. Patricii non dederunt potestatem in urbe. Ergo plebs pugnaverunt cum patriciis. Plebs non remanserunt in urbe. Plebs venerunt in Sacrum Montem. Patricii exclamaverunt: Venite in urbem! Sed plebs remansit in Monte Sacro. Magni patricii venerunt ad plebem. Dixerunt: VENITE! venite in urbem Romanam! Sed plebs remansit in Monte Sacro. Ergo patricii creaverunt officium novum. Creaverunt tribunos plebis. Fuerunt duo tribuni plebis. Ergo plebs non remansit in Monte Sacro. Plebs venit in urbem. Plebs venit cum tribunis. Tribuni magnam potestatem habuerunt. Consules habuerunt magnam potestatem. Sed tribuni etiam habuerunt magnam potestatem.",
     "explanation": "**Nouns in the vocabulary:** Until now we have learned only the nominative singular of each noun. Now that we have the ablative, we will learn both the nominative and the ablative singular. The ablative singular does two things for us: it shows which **declension** a noun belongs to (so we know which set of endings to use), and it shows the **base** on which we build the endings (the ablative singular minus its ending). **Ablative plurals:** The ablative plural endings for the three families are: 1. **-is** (e.g., nautis), 2. **-is** (e.g., agnis), 3. **-ibus** (e.g., civibus). So the full ablative is: family 1, singular -a, plural -is; family 2, singular -o, plural -is; family 3, singular -i or -e, plural -ibus. Notice that some third declension nouns take -i and some take -e; this makes little difference to us for now. **Expletive \"there\":** In a sentence like Non sunt reges in terra Romana, we can translate either \"Kings are not in the Roman land\" or \"There are not kings in the Roman land.\" The word **there** in the second version is just a filler that English uses to start a sentence with the verb \"to be.\" Latin does fine without it. Also notice that **plebs** is collective: the form is singular but the sense is plural, so Most uses both singular and plural verbs with it.",
     "keyTerms": [
      {
       "term": "fecit",
       "def": "made, did"
      },
      {
       "term": "sunt",
       "def": "are"
      },
      {
       "term": "voluit",
       "def": "wished, willed"
      },
      {
       "term": "nunc",
       "def": "now"
      },
      {
       "term": "civis",
       "def": "citizen"
      },
      {
       "term": "novus",
       "def": "new"
      },
      {
       "term": "potestas",
       "def": "power"
      },
      {
       "term": "officium",
       "def": "office"
      },
      {
       "term": "consul",
       "def": "consul"
      },
      {
       "term": "tribunus",
       "def": "tribune"
      },
      {
       "term": "dives",
       "def": "rich"
      },
      {
       "term": "plebs",
       "def": "plebeian(s)"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'potestas' mean in this lesson?",
       "accept": [
        "power"
       ],
       "answer": "power",
       "why": "The vocabulary glosses potestas as 'power': 'Patricii etiam magnam potestatem habuerunt.'",
       "src": "Most",
       "id": "lat-1-5-e1"
      },
      {
       "type": "type",
       "q": "What does the Latin word 'voluit' mean in this lesson?",
       "accept": [
        "wished",
        "willed",
        "wished, willed",
        "he wished"
       ],
       "answer": "wished",
       "why": "The vocabulary glosses voluit as 'wished, willed', and the plebs 'voluerunt potestatem'.",
       "src": "Most",
       "id": "lat-1-5-e2"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'new'.",
       "accept": [
        "novus",
        "novum"
       ],
       "answer": "novus",
       "why": "The vocabulary gives novus = new: 'Ergo patricii creaverunt officium novum.'",
       "src": "Most",
       "id": "lat-1-5-e3"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'citizen'.",
       "accept": [
        "civis"
       ],
       "answer": "civis",
       "why": "The vocabulary gives civis = citizen: 'In urbe Romana cives pugnaverunt cum civibus.'",
       "src": "Most",
       "id": "lat-1-5-e4"
      },
      {
       "type": "type",
       "q": "Quot (how many) consules fecerunt Romani?",
       "accept": [
        "duos",
        "duo",
        "two"
       ],
       "answer": "duos",
       "why": "The story says 'Romani fecerunt consules duos.'",
       "src": "Most",
       "id": "lat-1-5-e5"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Ergo patricii creaverunt officium ___.",
       "accept": [
        "novum"
       ],
       "answer": "novum",
       "why": "The story reads 'Ergo patricii creaverunt officium novum.'",
       "src": "Most",
       "id": "lat-1-5-e6"
      },
      {
       "type": "mc",
       "q": "Which ending marks the ablative PLURAL of a third declension noun like civis?",
       "choices": [
        "-ibus",
        "-is",
        "-am",
        "-o"
       ],
       "answer": 0,
       "why": "Most lists the ablative plural endings as 1. -is, 2. -is, 3. -ibus, e.g. civibus.",
       "src": "Most",
       "id": "lat-1-5-e7"
      }
     ],
     "id": "lat-1-5",
     "examples": []
    },
    {
     "title": "Nominative Singular & Plural",
     "summary": "The Romans go to war with the Aequi; when the Roman army is trapped, the senate makes Cincinnatus dictator, and after he rescues the army he resigns and returns to his farm.",
     "lead": "Watch the nominative (subject) endings across the three declensions, both singular and plural.",
     "original": "Romani habuerunt bellum cum Aequis. Consul Romanus venit cum exercitu Romano ad pugnam. Exercitus Romanus pugnavit cum Aequis. Aequi pugnaverunt cum Romanis. Aequi viri fortes fuerunt. Sed Romani etiam viri fortes fuerunt. Ergo viri fortes pugnaverunt cum viris fortibus. Sed exercitus Romanus venit in magnum periculum. Viri Romani exclamaverunt: in magno periculo sumus! Sed viri Romani fortes fuerunt. Et in urbe Romana fuit senatus Romanus. Viri boni fuerunt in senatu Romano. Ergo senatus Romanus fecit consilium: Dictatorem creaverunt. Cincinnatus fuit vir bonus, vir fortis. In veritate, Cincinnatus fuit Romanus bonus. Legati ex senatu venerunt ad Cincinnatum. Cincinnatus fuit in agris. Legati ex senatu dixerunt quod exercitus Romanus in periculo magno fuit. Dixerunt quod senatus creavit Cincinnatum dictatorem. Ergo Cincinnatus non remansit in agris. Cincinnatus fuit dictator. Cincinnatus venit cum viris fortibus. Cincinnatus pugnavit cum Aequis. Cincinnatus vicit Aequos. Sed Cincinnatus non remansit Dictator. Cincinnatus non voluit magnam potestatem. Cincinnatus voluit agros bonos. Ergo Cincinnatus venit in senatum. Cincinnatus dixit in senatu quod non voluit magnam potestatem. Cincinnatus venit rursus in agros. Nunc Cincinnatus non est Dictator.",
     "explanation": "**Nominative endings.** We have been using the **nominative** endings for the subject for some time now, so let us add them up for the three declensions we know. First declension: singular **-a** (nauta), plural **-ae** (nautae). Second declension: singular **-us** or **-r** (agnus, ager, vir), plural **-i** (agni, agri, viri). Third declension: plural **-es**. Notice that we did not give an ending for the **nominative singular of the third declension**. That is because there is so large a variety: we must learn each word as it comes. A few words we have already met do not fit the table above; do not worry about them now, since we can use them easily even before knowing all about them. But let us be sure to learn the **nominative and the ablative singular** of each word, and then they will not be hard to handle. **The preposition ex.** Notice that this preposition has two forms, **e** and **ex**. Use **e** before consonants, and **ex** before vowels (and sometimes before consonants as well).",
     "keyTerms": [
      {
       "term": "Aequi",
       "def": "the Aequi (a people)"
      },
      {
       "term": "fortis",
       "def": "brave, strong"
      },
      {
       "term": "periculum",
       "def": "danger"
      },
      {
       "term": "senatus",
       "def": "senate"
      },
      {
       "term": "consilium",
       "def": "plan"
      },
      {
       "term": "dictator",
       "def": "dictator"
      },
      {
       "term": "creavit",
       "def": "created, made"
      },
      {
       "term": "legatus",
       "def": "legate"
      },
      {
       "term": "ager",
       "def": "field, farm"
      },
      {
       "term": "ex",
       "def": "from, out from"
      },
      {
       "term": "vicit",
       "def": "conquered"
      },
      {
       "term": "rursus",
       "def": "again"
      }
     ],
     "exercises": [
      {
       "type": "type",
       "q": "What does the Latin word 'periculum' mean in this lesson?",
       "accept": [
        "danger",
        "a danger"
       ],
       "answer": "danger",
       "why": "The vocabulary glosses periculum as 'danger'.",
       "src": "Most",
       "id": "lat-1-6-e1"
      },
      {
       "type": "type",
       "q": "Give the Latin word Most uses for 'plan'.",
       "accept": [
        "consilium"
       ],
       "answer": "consilium",
       "why": "The vocabulary glosses consilium as 'plan'.",
       "src": "Most",
       "id": "lat-1-6-e2"
      },
      {
       "type": "type",
       "q": "What does the Latin word 'vicit' mean in this lesson?",
       "accept": [
        "conquered",
        "he conquered"
       ],
       "answer": "conquered",
       "why": "The vocabulary glosses vicit as 'conquered'.",
       "src": "Most",
       "id": "lat-1-6-e3"
      },
      {
       "type": "type",
       "q": "Quis vicit Aequos?",
       "accept": [
        "Cincinnatus"
       ],
       "answer": "Cincinnatus",
       "why": "The story says: 'Cincinnatus vicit Aequos.'",
       "src": "Most",
       "id": "lat-1-6-e4"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Romani habuerunt ___ cum Aequis.",
       "accept": [
        "bellum"
       ],
       "answer": "bellum",
       "why": "The story opens: 'Romani habuerunt bellum cum Aequis.'",
       "src": "Most",
       "id": "lat-1-6-e5"
      },
      {
       "type": "cloze",
       "q": "Fill the blank from the story.",
       "text": "Cincinnatus non voluit magnam ___.",
       "accept": [
        "potestatem"
       ],
       "answer": "potestatem",
       "why": "The story says: 'Cincinnatus non voluit magnam potestatem.'",
       "src": "Most",
       "id": "lat-1-6-e6"
      },
      {
       "type": "mc",
       "q": "Which nominative ending marks the plural subject of the second declension (as in 'agni, agri, viri')?",
       "choices": [
        "-ae",
        "-i",
        "-es",
        "-a"
       ],
       "answer": 1,
       "why": "Most's table gives the second declension plural nominative as -i (agni, agri, viri).",
       "src": "Most",
       "id": "lat-1-6-e7"
      }
     ],
     "id": "lat-1-6",
     "examples": []
    }
   ]
  }
 ]
});
